spring:
  application:
    name: hahaloh-back
  datasource:
    url: jdbc:postgresql://localhost:30007/dev  # Укажите внешний IP-адрес машины
    driverClassName: org.postgresql.Driver
    username: loh  # Имя пользователя, как в манифесте
    password: hahaloh  # Пароль, как в манифесте
springdoc:
  swagger-ui:
    url: http://localhost:8080
