spring:
  application:
    name: hahaloh-back
  datasource:
    url: jdbc:postgresql://postgres:5432/dev
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
springdoc:
  swagger-ui:
    enabled: true
    path: /api/doc-ui/
  api-docs:
    enabled: true
server:
  servlet:
    session:
      timeout: 5m

spring.mvc:
  async:
    request-timeout: 60000

app:
  server-url: https://manatee-good-quagga.ngrok-free.app

hh:
  client-id: ${HH_CLIENT_ID}
  client-secret: ${HH_CLIENT_SECRET}
  redirect-uri: "zhendorenko.space/api/oauth/hh/callback"
  authorization-grant-type: authorization_code
  scope: "basic"
  client-name: HeadHunter
  authorization-uri: https://hh.ru/oauth/authorize
  token-uri: https://hh.ru/oauth/token
  user-info-uri: https://api.hh.ru/me
  user-name-attribute: id
