spring:
  application:
    name: hahaloh-back
  datasource:
    url: jdbc:postgresql://localhost:30007/dev
    driverClassName: org.postgresql.Driver
    username: loh  # Имя пользователя, как в манифесте
    password: hahaloh  # Пароль, как в манифесте
app:
  server-url: http://localhost:8080