spring:
  application:
    name: hahaloh-back
  datasource:
    url: jdbc:postgresql://postgres:5432/dev
    driverClassName: org.postgresql.Driver
    username: loh
    password: hahaloh
  sql:
    init:
      mode: always
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
springdoc:
  swagger-ui:
    enabled: true
    path: /api/doc-ui/
    url: https://manatee-good-quagga.ngrok-free.app
  api-docs:
    enabled: true
server:
  servlet:
    session:
      timeout: 5m

spring.mvc:
  async:
    request-timeout: 60000
