name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Docker image tag
        id: image_tag
        run: |
          TAG="v$(date +'%Y%m%d%H%M%S')"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t balalaika7771/hahaloh-back:${{ env.TAG }} .
          docker tag balalaika7771/hahaloh-back:${{ env.TAG }} balalaika7771/hahaloh-back:latest

      - name: Push Docker image with version tag
        run: |
          docker push balalaika7771/hahaloh-back:${{ env.TAG }}
          docker push balalaika7771/hahaloh-back:latest

      - name: Send update message to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          IMAGE_TAG: ${{ env.TAG }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
          -d chat_id="${TELEGRAM_CHAT_ID}" \
          -d text="Образ бэка версии $IMAGE_TAG загружен в Docker Hub"
